Repository GlacioHack/GeoUtils, pull requests merged in 2021-05, with the labels that each got.

#165 Simplify reproject resampling argument to accept strings
  geoutils/georaster.py
  tests/test_georaster.py
Labels: enhancement

#157 Fix type hints and conform to pep-8
  dev-requirements.txt
  environment.yml
  geoutils/georaster.py
  tests/test_georaster.py
  tests/test_satimg.py
Labels: bug, enhancement

#179 Improve documentation
  .gitignore
  .readthedocs.yml
  dev-requirements.txt
  doc/Makefile
  doc/raster-basics.rst
  doc/source/api.rst
  doc/source/code/index_example.py
  doc/source/code/raster-basics_cropping_and_reprojecting.py
  doc/source/code/raster-basics_open_file.py
  doc/source/code/satimg-basics_open_file.py
  doc/source/code/vector-basics_open_file.py
  doc/source/conf.py
  doc/source/index.rst
  doc/source/raster-basics.rst
  doc/source/satimg-basics.rst
  doc/source/vector-basics.rst
  geoutils/georaster.py
  tests/test_docs.py
Labels: documentation, enhancement

#173 Adding overloading functionality for add, sub and neg
  geoutils/georaster.py
  tests/test_georaster.py
  tests/test_satimg.py
Labels: enhancement

#184 Add link to documentation on README.
  README.md
Labels: enhancement

#181 Enable multithreading for `Raster.reproject()` by default.
  geoutils/georaster.py
Labels: enhancement

#186 Add CI for windows, macos and linux, for multiple python versions
  .github/workflows/python-app.yml
  environment.yml
  tests/test_docs.py
Labels: enhancement, test-suite

#187 Add `compress` and `tiled` arguments for `Raster.save()` and enable compression by default.
  geoutils/georaster.py
Labels: enhancement

#188 Add support to crop rasters with vectors, and minor other improvements
  geoutils/georaster.py
  geoutils/geovector.py
  tests/test_georaster.py
  tests/test_geovector.py
Labels: enhancement

#189 Fix `Raster.info(stats=True)` warning
  geoutils/georaster.py
  tests/test_georaster.py
Labels: bug

#195 Add a function to merge different bounds
  geoutils/projtools.py
  tests/test_projtools.py
Labels: bug, enhancement
